# Generated by Django 6.0.1 on 2026-01-29 18:09

import uuid
from django.db import migrations, models


def generate_unique_public_ids(apps, schema_editor):
    """Generate unique UUIDs for existing votes"""
    Vote = apps.get_model('Meeting', 'Vote')
    for vote in Vote.objects.all():
        vote.public_id = uuid.uuid4()
        vote.save(update_fields=['public_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0005_vote_results_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='hide_from_public_report',
            field=models.BooleanField(default=False, help_text='Hide this vote from public meeting reports'),
        ),
        migrations.AddField(
            model_name='vote',
            name='majority_threshold',
            field=models.CharField(blank=True, choices=[('simple', 'Simple Majority'), ('two_thirds', 'Two-Thirds Majority')], help_text='For YNA votes: threshold to determine pass/fail', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='num_seats',
            field=models.PositiveSmallIntegerField(blank=True, help_text='For STV votes: number of seats to elect', null=True),
        ),
        # Step 1: Add public_id field as nullable without unique constraint
        migrations.AddField(
            model_name='vote',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public identifier for shareable reports', null=True),
        ),
        # Step 2: Generate unique UUIDs for all existing votes
        migrations.RunPython(generate_unique_public_ids, reverse_code=migrations.RunPython.noop),
        # Step 3: Make the field non-nullable and unique
        migrations.AlterField(
            model_name='vote',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public identifier for shareable reports', unique=True),
        ),
    ]
