# Generated by Django 6.0.1 on 2026-01-30 16:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0006_vote_hide_from_public_report_vote_majority_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenset',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public identifier for shareable meeting reports', unique=True),
        ),
    ]
