version: '3'
services:
  web:
    build:
      context: .
      dockerfile:  /docker/django_server/Dockerfile
    command: bash -c "python manage.py makemigrations Meeting; python manage.py migrate; echo yes | python manage.py collectstatic; python manage.py runserver 0.0.0.0:8000;"
    ports:
     - "8000:8000"
    links:
      - redis:redis
      - database:database
    environment:
      - DATABASE_PASSWORD
      - SECRET_KEY
      - DATABASE_USER=django
    depends_on:
      - redis
      - database
    restart: always
    volumes:
        - static_volume:/srv/static
  redis:
    image: "redis:alpine"
    restart: always
  nginx:
    build:
      context: .
      dockerfile:  /docker/nginx/Dockerfile
    ports:
     - "80:80"
    restart: always
    volumes:
        - static_volume:/srv/api/static
  database:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_DATABASE: "democrapp"
      MYSQL_USER: "django"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
    restart: always
volumes:
    static_volume:
