version: '3'
services:
  web:
    build:
      context: .
      dockerfile:  /docker/django_server/Dockerfile
    ports:
     - "8000:8000"
    links:
      - redis:redis
  redis:
    image: "redis:alpine"
  nginx:
    build:
      context: .
      dockerfile:  /docker/nginx/Dockerfile
    ports: 
     - "80:80"
